<?php

declare(strict_types=1);

namespace App\Services\OwnerApp;

use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;

/**
 * The shop's VAPID key pair (RFC 8292): the identity the push services know
 * this server by.
 *
 *   owner_app_vapid_public    the P-256 public key, uncompressed (65 bytes),
 *                             base64url. Handed to the browser, which passes
 *                             it to pushManager.subscribe() — it is public by
 *                             design.
 *   owner_app_vapid_private   the private key as PEM, ENCRYPTED with the app
 *                             key (Crypt::encryptString). Never sent anywhere;
 *                             it only signs the JWT on each push.
 *
 * Generated by the migration with PHP's own openssl, no library. If APP_KEY
 * ever changes the private key can no longer be decrypted; pair() then makes a
 * new pair, and every device simply subscribes again the next time the app is
 * opened (the app compares the key it subscribed with to the one it is given).
 */
final class VapidKeys
{
    public const PUBLIC = 'owner_app_vapid_public';

    public const PRIVATE = 'owner_app_vapid_private';

    /** @var array{public:string, pem:string}|null */
    private static ?array $memo = null;

    /** @return array{public:string, pem:string}|null the pair, or null if openssl cannot make one */
    public static function pair(): ?array
    {
        if (self::$memo !== null) {
            return self::$memo;
        }

        try {
            $rows = DB::table('settings')->whereIn('key', [self::PUBLIC, self::PRIVATE])->pluck('value', 'key');
            $public = (string) ($rows[self::PUBLIC] ?? '');
            $sealed = (string) ($rows[self::PRIVATE] ?? '');

            if ($public !== '' && $sealed !== '') {
                $pem = Crypt::decryptString($sealed);
                if (openssl_pkey_get_private($pem) !== false) {
                    return self::$memo = ['public' => $public, 'pem' => $pem];
                }
            }
        } catch (\Throwable) {
            // Unreadable (APP_KEY changed) or no table yet: make a fresh pair.
        }

        return self::generate();
    }

    public static function publicKey(): ?string
    {
        return self::pair()['public'] ?? null;
    }

    /** @return array{public:string, pem:string}|null */
    public static function generate(): ?array
    {
        $key = openssl_pkey_new(['curve_name' => 'prime256v1', 'private_key_type' => OPENSSL_KEYTYPE_EC]);

        if ($key === false || ! openssl_pkey_export($key, $pem)) {
            return null;
        }

        $public = WebPush::b64u(WebPush::publicPoint($key));

        try {
            foreach ([self::PUBLIC => $public, self::PRIVATE => Crypt::encryptString($pem)] as $k => $v) {
                DB::table('settings')->updateOrInsert(
                    ['key' => $k],
                    ['value' => $v, 'autoload' => false, 'updated_at' => now(), 'created_at' => now()],
                );
            }
            \App\Models\Setting::flushMap();
        } catch (\Throwable) {
            return null;
        }

        // A subscription is bound to the key it was made with; under a new key
        // every push to it is refused. Each app re-subscribes on its next open.
        // The shop app's subscriptions (Lane NT) were made with the same key.
        foreach (['owner_app_push_subscriptions', 'site_app_push_subscriptions'] as $table) {
            try {
                DB::table($table)->delete();
            } catch (\Throwable) {
            }
        }

        return self::$memo = ['public' => $public, 'pem' => $pem];
    }

    public static function forget(): void
    {
        self::$memo = null;
    }
}
