export DB_CONNECTION=sqlite
export DB_DATABASE=/home/user/lane-bn2/storage/bn2-logs/preview.sqlite
export APP_ENV=local
export APP_DEBUG=true
export APP_KEY=base64:CkWozlwlsY0bVI4HQg5sdiSGBMh5kctUnNUWJJBJCD0=
export SESSION_DRIVER=file
export CACHE_STORE=file
export KBB_PUBLIC_PATH=/home/user/lane-bn2/public-web-root
export APP_URL=http://127.0.0.1:8731
export BN2_PORT=8731
