<?php

declare(strict_types=1);

/**
 * The bulk previews the owner reviews — rendered, asserted, written to disk.
 *
 * A test and not a script, for the reason InvoicePreviewsTest gives: the owner
 * looks at a rendered copy before a package ships, and a preview generated by
 * hand goes stale the first time somebody is in a hurry. Running the suite
 * regenerates every file from the same route the store serves.
 *
 * WHAT TO LOOK AT ON THESE, and it is not the same thing as on a single
 * document. Open one and press Print. The question is the PAGE COUNT: three
 * orders must be three pages, with no order straddling a break and no blank
 * page at the end. That is the one defect this feature can have that is
 * invisible on screen — docs/GC-BULK-PRINTING.md records the counts and the
 * geometry Chromium reported for exactly these files.
 *
 * FOUR ORDERS, DELIBERATELY AWKWARD. One ordinary card order, one cash-on-
 * delivery order so the label run contains a COD box and the invoice run a
 * surcharge, one gift going to a different address, and one placed in Arabic so
 * a mixed-language invoice batch is something the owner can actually see. A
 * batch that only ever gets reviewed as four copies of the same order is a
 * batch whose Arabic sheet nobody has looked at.
 *
 * DETERMINISM IS PART OF THE TEST. Fixed primary keys and a fixed clock, so a
 * green run does not leave modified files in `git status` — noise that trains
 * everyone to ignore a diff in exactly the files the owner is supposed to
 * review. InvoicePreviewsTest's own header explains why the ids have to be
 * explicit: SQLite resets the key on rollback and MySQL does not.
 */

use App\Models\AdminUser;
use App\Models\Order;
use App\Services\SettingsService;
use Illuminate\Support\Carbon;
use Tests\Support\BulkDocumentAdminRoutes;

function gcPreviewDir(): string
{
    $dir = base_path('docs/gc-bulk-shots');

    if (! is_dir($dir)) {
        mkdir($dir, 0775, true);
    }

    return $dir;
}

/** The four orders a batch preview is built from. @return list<Order> */
function gcPreviewOrders(): array
{
    $common = [
        'currency' => 'AED',
        'status' => 'processing',
        'shipping_method' => 'Standard delivery (1–3 working days)',
        'tax_total' => 0,
    ];

    $orders = [];

    $orders[] = Order::create(array_merge($common, [
        'id' => 20501,
        'order_number' => 'KBB-20501',
        'email' => 'aisha.khan@example.com',
        'phone' => '+971 50 123 4567',
        'locale' => 'en',
        'billing_address' => [
            'first_name' => 'Aisha', 'last_name' => 'Khan',
            'line1' => 'Apartment 1204, Marina Heights', 'city' => 'Dubai',
            'state' => 'Dubai', 'country' => 'AE', 'phone' => '+971 50 123 4567',
        ],
        'subtotal' => 39800, 'shipping_total' => 2000, 'total' => 41800,
        'payment_method' => 'card', 'payment_method_title' => 'Card',
        'created_at' => '2026-09-14 09:41:00',
    ]));

    // Cash on delivery: the label run gets a COLLECT box, the invoice a fee.
    $orders[] = Order::create(array_merge($common, [
        'id' => 20502,
        'order_number' => 'KBB-20502',
        'email' => 'mariam.s@example.com',
        'phone' => '+971 52 400 1188',
        'locale' => 'en',
        'billing_address' => [
            'first_name' => 'Mariam', 'last_name' => 'Al Suwaidi',
            'line1' => 'Villa 12, Street 4, Jumeirah 1', 'city' => 'Dubai',
            'state' => 'Dubai', 'country' => 'AE', 'phone' => '+971 52 400 1188',
        ],
        'subtotal' => 19900, 'shipping_total' => 2000, 'fee_total' => 1550,
        'total' => 23450,
        'payment_method' => 'cod', 'payment_method_title' => 'Cash on delivery',
        'created_at' => '2026-09-14 11:02:00',
    ]));

    // A gift, going somewhere other than the buyer.
    $orders[] = Order::create(array_merge($common, [
        'id' => 20503,
        'order_number' => 'KBB-20503',
        'email' => 'omar.h@example.com',
        'phone' => '+971 56 771 2390',
        'locale' => 'en',
        'billing_address' => [
            'first_name' => 'Omar', 'last_name' => 'Haddad',
            'line1' => 'Office 902, Boulevard Plaza', 'city' => 'Dubai',
            'state' => 'Dubai', 'country' => 'AE', 'phone' => '+971 56 771 2390',
        ],
        'shipping_address' => [
            'first_name' => 'Noura', 'last_name' => 'Al Mansoori',
            'line1' => 'Villa 7, Street 21', 'line2' => 'Al Barsha South 2',
            'city' => 'Dubai', 'state' => 'Dubai', 'country' => 'AE',
            'phone' => '+971 55 987 6543',
        ],
        'subtotal' => 26400, 'shipping_total' => 2000, 'gift_fee' => 1500,
        'is_gift' => true,
        'gift_note' => "Happy birthday, Mama.\nLove from all of us x",
        'customer_note' => 'Please ring the doorbell twice — the buzzer is broken.',
        'total' => 29900,
        'payment_method' => 'card', 'payment_method_title' => 'Card',
        'created_at' => '2026-09-14 15:18:00',
    ]));

    // Placed in Arabic. Its INVOICE prints in Arabic inside an otherwise
    // English batch; its packing slip does not, and that is the rule.
    $orders[] = Order::create(array_merge($common, [
        'id' => 20504,
        'order_number' => 'KBB-20504',
        'email' => 'layla@example.com',
        'phone' => '+971 54 310 7755',
        'locale' => 'ar',
        'billing_address' => [
            'first_name' => 'ليلى', 'last_name' => 'الحمادي',
            'line1' => 'شارع 21، فيلا 7', 'line2' => 'البرشاء جنوب 2',
            'city' => 'دبي', 'state' => 'دبي', 'country' => 'AE',
            'phone' => '+971 54 310 7755',
        ],
        'subtotal' => 13000, 'shipping_total' => 2000, 'total' => 15000,
        'payment_method' => 'card', 'payment_method_title' => 'Card',
        'created_at' => '2026-09-14 17:45:00',
    ]));

    foreach ($orders as $i => $order) {
        $order->items()->create([
            'name' => 'Rice Daily Moisturizing Toner 150ml',
            'brand' => 'Haruharu Wonder', 'sku' => 'HH-RT-150',
            'quantity' => 1 + ($i % 2), 'unit_price' => 19900,
            'subtotal' => 19900 * (1 + ($i % 2)), 'total' => 19900 * (1 + ($i % 2)),
        ]);
        $order->items()->create([
            'name' => 'Centella Ampoule',
            'brand' => 'SKIN1004', 'sku' => 'SK-CA-030',
            'variant_attributes' => ['30ml'],
            'quantity' => 1, 'unit_price' => 6500,
            'subtotal' => 6500, 'total' => 6500,
        ]);
    }

    return $orders;
}

it('renders a batch of each of the four documents and saves them for review', function () {
    Carbon::setTestNow(Carbon::parse('2026-09-15 11:20:00'));

    BulkDocumentAdminRoutes::wire(app());

    $settings = app(SettingsService::class);
    $settings->set('invoice_business_name', 'K Beauty Bliss Trading LLC');
    $settings->set('invoice_address', "Office 1902, Burlington Tower\nBusiness Bay, Dubai\nUnited Arab Emirates");
    $settings->set('invoice_trn', '100123456700003');
    $settings->set('invoice_email', 'info@kbeautybliss.com');
    $settings->set('invoice_phone', '+971 58 505 2611');
    $settings->set('invoice_website', 'kbeautybliss.com');
    $settings->set('invoice_footer', "Payment received in full — no further amount is due.");

    $orders = gcPreviewOrders();
    $ids = implode(',', array_map(fn (Order $o) => $o->id, $orders));

    test()->actingAs(AdminUser::create([
        'name' => 'Preview Owner',
        'email' => 'gc-preview-owner@example.test',
        'password' => 'secret-secret',
        'role' => 'owner',
    ]), 'admin');

    /*
     * THE INVOICE RUN IS LAST, AND THE ORDER IS PART OF WHAT THESE SHOW.
     * Printing a packing slip, a delivery note or a label allocates nothing, so
     * rendering those three first means their previews carry NO invoice
     * reference — which is the rule made visible. The invoice run then mints
     * one number per order, and a packing slip reprinted afterwards would show
     * it. Generating the invoice first would have put an invoice number on all
     * four previews and quietly hidden the distinction.
     */
    $files = [
        'packing-slip' => 'bulk-packing-slips.html',
        'delivery-note' => 'bulk-delivery-notes.html',
        'dispatch-label' => 'bulk-dispatch-labels.html',
        'invoice' => 'bulk-invoices.html',
    ];

    foreach ($files as $type => $name) {
        $html = (string) test()
            ->get('/admin-api/orders-bulk-documents?type=' . $type . '&ids=' . $ids)
            ->assertStatus(200)
            ->getContent();

        // FOUR SHEETS, EVERY TIME. The count is the assertion that matters: a
        // preview quietly missing an order would still look like a document.
        $class = $type === 'dispatch-label' ? 'class="sheet lbl"' : 'class="sheet"';

        expect(substr_count($html, $class))->toBe(4, $name . ' does not hold four sheets')
            ->and($html)->toContain('.bulkdoc > .sheet { break-after: page; page-break-after: always; }')
            ->and($html)->toContain('.bulkdoc > .sheet:last-child { break-after: auto; page-break-after: auto; }');

        foreach ($orders as $order) {
            expect($html)->toContain((string) $order->order_number);
        }

        file_put_contents(gcPreviewDir() . '/' . $name, $html);
    }

    // The Arabic order's INVOICE is Arabic; its packing slip is not. Read off
    // the two files that were just written, so the preview is what is asserted.
    $invoices = (string) file_get_contents(gcPreviewDir() . '/bulk-invoices.html');
    $slips = (string) file_get_contents(gcPreviewDir() . '/bulk-packing-slips.html');

    /*
     * dir IS NOT ASSERTED TO BE rtl, AND THAT IS THE CORRECT ANSWER TODAY.
     * Locale::direction() answers from the shop's SECOND switch, not from the
     * language: Arabic can be on while the mirrored layout is still being
     * built, which is the state this shop is in, so an Arabic sheet is
     * lang="ar" dir="ltr". document.blade.php's own header says the same thing
     * about the single documents. Pinning dir="rtl" here would pin a state the
     * shop is not in and would go red the day another lane turns mirroring on —
     * which is the day this should start reading rtl by itself.
     */
    expect(substr_count($invoices, 'lang="ar"'))->toBe(1)
        ->and(substr_count($invoices, 'lang="en"'))->toBeGreaterThan(1)
        ->and(str_contains($slips, 'lang="ar"'))->toBeFalse();

    // The cash-on-delivery label carries its COLLECT box and the other three
    // labels do not — the one figure on a label that a driver acts on.
    $labels = (string) file_get_contents(gcPreviewDir() . '/bulk-dispatch-labels.html');

    expect(substr_count($labels, 'class="cod"'))->toBe(1);

    Carbon::setTestNow();
});
