<?php

declare(strict_types=1);

/**
 * The previews the owner reviews — rendered, asserted, and written to disk.
 *
 * A test and not a script, for the same reason OrderEmailPreviewsTest is one:
 * the owner looks at a rendered copy of every document before a package ships,
 * and a preview generated by hand goes stale the first time somebody is in a
 * hurry — the reviewed file and the printed page stop being the same thing,
 * silently. Running the suite regenerates all four files from the same routes
 * and the same Mailable the store actually uses.
 *
 * Written to docs/invoice-previews/. Open either .html in a browser and press
 * print: what the dialog shows is what the owner gets.
 *
 * The order behind them is deliberately awkward rather than tidy — two lines, a
 * variant, a coupon discount, gift wrapping, a cash-on-delivery surcharge, a
 * gift message, an order note, and a delivery address belonging to somebody
 * other than the buyer — because a document that only ever gets reviewed
 * against the simplest possible order is a document whose discount row nobody
 * has ever seen.
 *
 * AND THE TOTAL IS 47350 FILS ON PURPOSE. AED 473.50. The storefront would
 * round that to AED 474, so a preview showing 474 anywhere is a preview of a
 * bug, and this file refuses to write one.
 */

use App\Mail\OrderInvoice;
use App\Models\AdminUser;
use App\Models\Order;
use App\Services\Invoices\InvoiceDocument;
use App\Services\SettingsService;
use Illuminate\Support\Carbon;
use Tests\Support\InvoiceAdminRoutes;

/** Where the rendered files land. */
function invoicePreviewDir(): string
{
    $dir = base_path('docs/invoice-previews');

    if (! is_dir($dir)) {
        mkdir($dir, 0775, true);
    }

    return $dir;
}

function invoicePreviewWrite(string $name, string $contents): string
{
    $path = invoicePreviewDir() . '/' . $name;

    file_put_contents($path, $contents);

    return $path;
}

it('renders the invoice, the packing slip and the emailed invoice, and saves them for review', function () {
    /*
     * A fixed clock, so the previews are byte-identical from one run to the
     * next. invoiced_at is stamped with now(); left real, the issue date
     * changes daily and every suite run leaves four modified files in
     * `git status` — noise that trains everyone to ignore a diff in exactly the
     * files the owner is supposed to review.
     */
    Carbon::setTestNow(Carbon::parse('2026-09-15 11:20:00'));

    InvoiceAdminRoutes::wire(app());

    // The business details a real store would have entered, so the preview
    // shows the masthead the owner will actually print.
    $settings = app(SettingsService::class);
    $settings->set('invoice_business_name', 'K Beauty Bliss Trading LLC');
    $settings->set('invoice_address', "Office 1902, Burlington Tower\nBusiness Bay, Dubai\nUnited Arab Emirates");
    $settings->set('invoice_trn', '100123456700003');
    $settings->set('invoice_email', 'info@kbeautybliss.com');
    $settings->set('invoice_phone', '+971 58 505 2611');
    $settings->set('invoice_website', 'kbeautybliss.com');
    $settings->set('invoice_footer', "Payment received in full — no further amount is due.\nReturns accepted within 14 days on unopened items.");

    $order = Order::create([
        /*
         * An explicit primary key, which nothing else in the suite bothers
         * with, because the previews carry it: each document links to the other
         * at /admin-api/orders/{id}/…, so a shifting id rewrites both files on
         * every run. On SQLite the key resets when RefreshDatabase rolls back
         * and on MySQL it does not, so the two suites would otherwise disagree
         * about the previews and leave four modified files behind whichever ran
         * last — noise that trains everyone to ignore a diff in exactly the
         * files the owner is supposed to review.
         */
        'id' => 10427,
        'order_number' => 'KBB-10427',
        'email' => 'aisha.khan@example.com',
        'phone' => '+971 50 123 4567',
        'status' => 'processing',
        'currency' => 'AED',
        'billing_address' => [
            'first_name' => 'Aisha', 'last_name' => 'Khan',
            'line1' => 'Apartment 1204, Marina Heights', 'city' => 'Dubai',
            'state' => 'Dubai', 'country' => 'AE', 'phone' => '+971 50 123 4567',
        ],
        // A gift sent to somebody else, which is why the packing slip has to
        // carry a second address and no prices at all.
        'shipping_address' => [
            'first_name' => 'Noura', 'last_name' => 'Al Mansoori',
            'line1' => 'Villa 7, Street 21', 'line2' => 'Al Barsha South 2',
            'city' => 'Dubai', 'state' => 'Dubai', 'country' => 'AE',
            'phone' => '+971 55 987 6543',
        ],
        'subtotal' => 46300,
        'discount_total' => 4000,
        'coupon_code' => 'GLOW10',
        'shipping_total' => 2000,
        'fee_total' => 3050,
        'gift_fee' => 1500,
        'is_gift' => true,
        'gift_note' => "Happy birthday, Mama.\nLove from all of us x",
        'customer_note' => 'Please ring the doorbell twice — the buzzer is broken.',
        'tax_total' => 0,
        'total' => 47350,
        'shipping_method' => 'Standard delivery (1–3 working days)',
        'payment_method' => 'cod',
        'payment_method_title' => 'Cash on delivery',
        'paid_at' => '2026-09-14 09:44:00',
        'created_at' => '2026-09-14 09:41:00',
    ]);

    $order->items()->create([
        'name' => 'Rice Daily Moisturizing Toner 150ml',
        'brand' => 'Haruharu Wonder', 'sku' => 'HH-RT-150',
        'quantity' => 2, 'unit_price' => 19900, 'subtotal' => 39800, 'total' => 39800,
    ]);

    $order->items()->create([
        'name' => 'Centella Ampoule',
        'brand' => 'SKIN1004', 'sku' => 'SK-CA-030',
        'variant_attributes' => ['30ml'],
        'quantity' => 1, 'unit_price' => 6500, 'subtotal' => 6500, 'total' => 6500,
    ]);

    $order = $order->fresh('items');

    expect($order->id)->toBe(10427, 'the previews embed the order id in their cross-links');

    // The figures the previews are a picture of. Asserted first, so a preview
    // can never be reviewed and approved against a total that is wrong.
    expect($order->subtotal)->toBe(46300)
        ->and($order->discount_total)->toBe(4000)
        ->and($order->shipping_total)->toBe(2000)
        ->and($order->gift_fee)->toBe(1500)
        ->and($order->fee_total)->toBe(3050)
        ->and($order->tax_total)->toBe(0)
        ->and($order->total)->toBe(47350);

    $admin = AdminUser::create([
        'name' => 'Preview Owner',
        'email' => 'invoice-preview@example.test',
        'password' => 'secret-secret',
        'role' => 'owner',
    ]);

    $written = [];

    /* ---- the printable invoice, through the route that serves it ---- */

    $invoice = test()->actingAs($admin, 'admin')
        ->get('/admin-api/orders/' . $order->id . '/invoice')
        ->assertOk()
        ->getContent();

    /*
     * "Invoice", not "Tax Invoice" — Lane DE.
     *
     * The heading used to be a literal. It is now InvoiceDocument::docType(),
     * which makes the tax-document claim only when the order really carries tax
     * that was charged or contained AND a TRN is recorded. This preview order
     * has the TRN and `tax_total` 0, which is the shipped state of the shop
     * (`tax_mode` is 'display'), so the honest heading is the plain word. The
     * owner overrides it with `invoice_doctype` once his accountant has told
     * him what this document is called; see InvoiceDocTypeTest.
     */
    expect($invoice)->toContain('>Invoice<')
        ->and($invoice)->not->toContain('Tax Invoice')
        ->and($invoice)->toContain('KBB-10427')
        ->and($invoice)->toContain('01000')
        ->and($invoice)->toContain('473.50')
        // Never the storefront's rounded AED 474 on a financial document.
        ->and($invoice)->not->toContain('474')
        ->and($invoice)->toContain('TRN 100123456700003')
        ->and($invoice)->not->toContain('<script');

    $written[] = invoicePreviewWrite('invoice.html', $invoice);

    /* ---- the packing slip: the same order, no prices ---- */

    $slip = test()->actingAs($admin, 'admin')
        ->get('/admin-api/orders/' . $order->id . '/packing-slip')
        ->assertOk()
        ->getContent();

    expect($slip)->toContain('Packing Slip')
        ->and($slip)->toContain('KBB-10427')
        ->and($slip)->toContain('Noura Al Mansoori')
        ->and($slip)->toContain('Happy birthday, Mama.')
        // The whole point of the second document.
        ->and($slip)->not->toContain('AED')
        ->and($slip)->not->toContain('473.50')
        ->and($slip)->not->toContain('Total');

    $written[] = invoicePreviewWrite('packing-slip.html', $slip);

    /* ---- the emailed invoice, both parts ---- */

    $order = $order->fresh('items');
    $mailable = new OrderInvoice($order);

    $emailHtml = (string) $mailable->render();

    expect($emailHtml)->toContain('KBB-10427')
        ->and($emailHtml)->toContain('01000')
        ->and($emailHtml)->toContain('473.50')
        ->and($emailHtml)->not->toContain('474')
        ->and($emailHtml)->not->toContain('<script');

    $written[] = invoicePreviewWrite('invoice-email.html', $emailHtml);

    $content = $mailable->content();
    $emailText = (string) view($content->text, array_merge($mailable->buildViewData(), $content->with))->render();

    expect($emailText)->toContain('KBB-10427')
        ->and($emailText)->toContain('473.50')
        ->and($emailText)->not->toContain('<span');

    $written[] = invoicePreviewWrite('invoice-email.txt', $emailText);

    expect($written)->toHaveCount(4);

    foreach ($written as $path) {
        expect(is_file($path))->toBeTrue()
            ->and(filesize($path))->toBeGreaterThan(400);
    }

    // The invoice and the emailed invoice describe one document: same number,
    // same total, rendered from one InvoiceDocument array.
    $doc = app(InvoiceDocument::class)->present($order);

    expect($doc['invoiceReference'])->toBe('01000')
        ->and($doc['totalFils'])->toBe(47350)
        ->and($invoice)->toContain($doc['invoiceReference'])
        ->and($emailHtml)->toContain($doc['invoiceReference']);

    Carbon::setTestNow();
});
