<?php

declare(strict_types=1);

/**
 * The Set, as it arrives in an inbox and as it comes off a printer. (Lane SE)
 *
 * A TEST AND NOT A SCRIPT, for the reason InvoicePreviewsTest and
 * OrderEmailPreviewsTest are tests: the owner looks at a rendered copy of every
 * document before a package ships, and a preview generated by hand goes stale
 * the first time somebody is in a hurry — the reviewed file and the sent
 * message stop being the same thing, silently. Running the suite regenerates
 * all four from the same Mailables and the same admin routes the shop uses.
 *
 * Written to docs/lane-se-shots/. tools/se-doc-shots.cjs photographs them at
 * 390px and 1280px and prints the measured numbers beside each one.
 *
 * ── THE ORDER IS ONE SET AND ONE ORDINARY PRODUCT, ON PURPOSE ──────────────
 *
 * Every picture then proves both halves at once: the member list is drawn under
 * the Set, and the ordinary line beside it is bare. A preview of an order that
 * is nothing but Sets would show a member list under everything and could not
 * tell the owner whether the rest of his shop had moved.
 *
 * The clock and the primary key are both fixed, for the reason
 * InvoicePreviewsTest fixes them: the documents carry an issue date and an
 * order id, and a preview that rewrites itself on every suite run is a diff
 * everybody learns to ignore in exactly the files that are meant to be read.
 */

use App\Mail\OrderConfirmation;
use App\Mail\OrderInvoice;
use App\Models\AdminUser;
use App\Models\Brand;
use App\Models\Order;
use App\Models\Product;
use App\Models\ProductSetItem;
use App\Services\SettingsService;
use App\Support\SetContents;
use Illuminate\Support\Carbon;
use Tests\Support\InvoiceAdminRoutes;

function setPreviewDir(): string
{
    $dir = base_path('docs/lane-se-shots');

    if (! is_dir($dir)) {
        mkdir($dir, 0775, true);
    }

    return $dir;
}

it('renders a Set order as an email and as a printed sheet, and saves them for review', function () {
    Carbon::setTestNow(Carbon::parse('2026-09-15 11:20:00'));

    InvoiceAdminRoutes::wire(app());

    $settings = app(SettingsService::class);
    $settings->set('invoice_business_name', 'K Beauty Bliss Trading LLC');
    $settings->set('invoice_address', "Office 1902, Burlington Tower\nBusiness Bay, Dubai\nUnited Arab Emirates");
    $settings->set('invoice_trn', '100123456700003');
    $settings->set('invoice_email', 'info@kbeautybliss.com');
    $settings->set('invoice_phone', '+971 58 505 2611');

    // firstOrCreate, because this shop's seed already carries both of these
    // brands and a preview must not depend on whether it ran.
    $anua = Brand::firstOrCreate(['slug' => 'anua'], ['name' => 'Anua']);
    $beauty = Brand::firstOrCreate(['slug' => 'beauty-of-joseon'], ['name' => 'Beauty of Joseon']);

    $member = function (string $name, int $fils, Brand $brand): Product {
        return Product::create([
            // Prefixed, for the same reason the brands are firstOrCreate'd:
            // the seeded catalogue already holds products with these names.
            'slug' => 'se-preview-'.\Illuminate\Support\Str::slug($name),
            'name' => $name,
            'type' => 'simple',
            'status' => 'publish',
            'is_visible' => true,
            'price' => $fils,
            'stock_status' => 'instock',
            'brand_id' => $brand->id,
        ]);
    };

    $toner = $member('Heartleaf 77 Soothing Toner 250ml', 9900, $anua);
    $serum = $member('Azelaic Acid 10 Serum 30ml', 7500, $beauty);
    $cream = $member('Relief Sun Rice + Probiotics SPF50', 6900, $beauty);

    $set = Product::create([
        'slug' => 'se-preview-glow-starter-set',
        'name' => 'Glow Starter Set',
        'type' => 'set',
        'status' => 'publish',
        'is_visible' => true,
        // Below the parts total of 9900 + (7500 x 2) + 6900 = 31800, so the
        // saving is a real number rather than zero.
        'price' => 26900,
        'stock_status' => 'instock',
    ]);

    ProductSetItem::create(['set_product_id' => $set->id, 'member_product_id' => $toner->id, 'quantity' => 1, 'position' => 0]);
    ProductSetItem::create(['set_product_id' => $set->id, 'member_product_id' => $serum->id, 'quantity' => 2, 'position' => 1]);
    ProductSetItem::create(['set_product_id' => $set->id, 'member_product_id' => $cream->id, 'quantity' => 1, 'position' => 2]);

    $plain = $member('Rice Daily Moisturizing Toner 150ml', 4900, $beauty);

    $order = Order::create([
        'id' => 10531,
        'order_number' => 'KBB-10531',
        'email' => 'aisha.khan@example.com',
        'phone' => '+971 50 123 4567',
        'status' => 'processing',
        'currency' => 'AED',
        'billing_address' => [
            'first_name' => 'Aisha', 'last_name' => 'Khan',
            'line1' => 'Apartment 1204, Marina Heights', 'city' => 'Dubai',
            'state' => 'Dubai', 'country' => 'AE', 'phone' => '+971 50 123 4567',
        ],
        'shipping_address' => [
            'first_name' => 'Aisha', 'last_name' => 'Khan',
            'line1' => 'Apartment 1204, Marina Heights', 'city' => 'Dubai',
            'state' => 'Dubai', 'country' => 'AE', 'phone' => '+971 50 123 4567',
        ],
        'subtotal' => 31800,
        'shipping_total' => 2000,
        'total' => 33800,
        'payment_method' => 'cod',
        'shipping_method' => 'Delivery Charges',
    ]);

    $order->items()->create([
        'product_id' => $set->id,
        'name' => $set->name,
        'sku' => 'KBB-SET-001',
        'quantity' => 1,
        'unit_price' => 26900,
        'subtotal' => 26900,
        'total' => 26900,
        // THE SNAPSHOT, written the way checkout writes it. Not a hand-built
        // array: a preview assembled differently from the real path is a
        // preview of something the shop does not send.
        'set_contents' => SetContents::snapshot($set->fresh(['setItems.member.brand'])),
    ]);

    $order->items()->create([
        'product_id' => $plain->id,
        'name' => $plain->name,
        'brand' => 'Beauty of Joseon',
        'sku' => 'BOJ-RICE-150',
        'quantity' => 1,
        'unit_price' => 4900,
        'subtotal' => 4900,
        'total' => 4900,
    ]);

    $order = $order->fresh(['items']);

    $admin = AdminUser::create([
        'name' => 'Preview Owner',
        'email' => 'set-previews@example.test',
        'password' => 'secret-secret',
        'role' => 'owner',
    ]);

    $files = [
        'email-order-confirmation.html' => (string) (new OrderConfirmation($order))->render(),
        'email-order-invoice.html' => (string) (new OrderInvoice($order))->render(),
        'print-invoice.html' => (string) $this->actingAs($admin, 'admin')
            ->get('/admin-api/orders/'.$order->id.'/invoice')->getContent(),
        'print-packing-slip.html' => (string) $this->actingAs($admin, 'admin')
            ->get('/admin-api/orders/'.$order->id.'/packing-slip')->getContent(),
    ];

    foreach ($files as $name => $body) {
        // A preview that did not render is a picture of nothing, and a picture
        // of nothing is the thing this file exists to stop being shipped.
        expect(str_contains($body, 'Glow Starter Set'))->toBeTrue("{$name} did not render the set line");
        expect(str_contains($body, '1 × Heartleaf 77 Soothing Toner 250ml'))->toBeTrue("{$name} did not render the member list");
        expect(str_contains($body, '2 × Azelaic Acid 10 Serum 30ml'))->toBeTrue("{$name} did not render the member quantity");
        expect(str_contains($body, 'Rice Daily Moisturizing Toner 150ml'))->toBeTrue("{$name} did not render the ordinary line");

        file_put_contents(setPreviewDir().'/'.$name, $body);
    }

    /*
     * AND THE ABANDONED-BASKET REMINDER, which this lane also changed. It is
     * not an order document — it describes a LIVE basket, and reads the set's
     * members off the live pivot for that reason — so it is built from the same
     * set through CartRecovery::basket(), the method the sender really calls.
     */
    $cart = \App\Models\Cart::create([
        'token' => 'lane-se-preview-cart',
        'currency' => 'AED',
        'status' => 'active',
        'shipping_country' => 'AE',
        'last_activity_at' => now(),
    ]);
    $cart->items()->create(['product_id' => $set->id, 'quantity' => 1, 'unit_price' => 26900]);
    $cart->items()->create(['product_id' => $plain->id, 'quantity' => 1, 'unit_price' => 4900]);

    $reminder = new \App\Mail\CartRecoveryReminder(
        'Your basket is waiting',
        "You left something behind.\nIt is still here.",
        app(\App\Services\CartRecovery::class)->basket((int) $cart->id),
        'https://kbeautybliss.test/cart/',
        'https://kbeautybliss.test/mail-preferences/cart/1',
    );

    $reminderHtml = (string) $reminder->render();

    expect(str_contains($reminderHtml, '1 × Heartleaf 77 Soothing Toner 250ml'))->toBeTrue('the reminder did not list the set members');
    expect(str_contains($reminderHtml, 'Rice Daily Moisturizing Toner 150ml'))->toBeTrue('the reminder did not show the ordinary line');

    file_put_contents(setPreviewDir().'/email-cart-recovery.html', $reminderHtml);

    $reminderContent = $reminder->content();
    file_put_contents(
        setPreviewDir().'/text-cart-recovery.txt',
        (string) view($reminderContent->text, array_merge($reminder->buildViewData(), $reminderContent->with))->render(),
    );

    // The plain-text twins are evidence too — they are what a text-only client
    // and a screen reader get, and no screenshot can show them.
    foreach (['order-confirmation' => new OrderConfirmation($order), 'order-invoice' => new OrderInvoice($order)] as $name => $mailable) {
        $content = $mailable->content();

        $text = (string) view($content->text, array_merge($mailable->buildViewData(), $content->with))->render();

        expect(str_contains($text, '  * 1 × Heartleaf 77 Soothing Toner 250ml'))->toBeTrue("{$name} text part did not list the members");

        file_put_contents(setPreviewDir().'/text-'.$name.'.txt', $text);
    }
});
