<?php

declare(strict_types=1);

namespace App\Services\Payments\Reconciliation;

use Carbon\CarbonImmutable;

/**
 * The stretch of time a reconciliation run covers.
 *
 * WHY THERE IS A WINDOW AT ALL. "Reconcile everything" is not a thing this
 * host can do. Every provider paginates, every provider rate-limits, and PHP
 * on shared hosting is killed somewhere between thirty seconds and two minutes
 * with no way to ask which. Years of history is tens of thousands of remote
 * rows, and a run that cannot finish reports nothing at all — which is
 * strictly worse than a run over last month that finishes.
 *
 * Both bounds are inclusive DAYS, expanded to the whole of each day in UTC. A
 * window of 2026-09-01..2026-09-01 is one day, not zero, because that is what
 * an owner typing the same date twice means.
 *
 * UTC, not the store's timezone, and that is deliberate rather than lazy.
 * Every provider timestamps in UTC (Stripe hands back a unix integer; Tabby
 * and Tamara hand back RFC3339), while `payments.created_at` is written by
 * Laravel in the app timezone. Converting one side to the other is a choice
 * that has to be made once, visibly, somewhere a reader can find it — so it is
 * made here, and the boundary is padded rather than argued about: see GRACE.
 * A payment that lands within a few hours of midnight must not become a
 * finding because two clocks disagreed about which day it was.
 */
final class ReconcileWindow
{
    /**
     * How far outside the window a LOCAL row is still allowed to match a
     * remote one.
     *
     * Not a fudge factor. A Tabby authorisation created at 23:58 and confirmed
     * by a webhook at 00:03 genuinely straddles the boundary, and the two sides
     * legitimately disagree about which day owns it. Without the grace, every
     * run would open with two findings per midnight — "the provider has one we
     * don't" and "we have one they don't" — for the same transaction. Twelve
     * hours is wider than any timezone offset this store can be configured to
     * and wider than any webhook retry schedule these three providers use.
     */
    public const GRACE_HOURS = 12;

    /** The longest window a single run will accept. */
    public const MAX_DAYS = 92;

    private function __construct(
        public readonly CarbonImmutable $from,
        public readonly CarbonImmutable $to,
    ) {}

    /**
     * @throws \InvalidArgumentException when the dates are unusable, which the
     *         controller turns into a 422 rather than a run that reports
     *         nothing for a reason nobody can see.
     */
    public static function between(string $from, string $to): self
    {
        try {
            $start = CarbonImmutable::parse(trim($from), 'UTC')->startOfDay();
            $end = CarbonImmutable::parse(trim($to), 'UTC')->endOfDay();
        } catch (\Throwable) {
            throw new \InvalidArgumentException('Those dates could not be read. Use YYYY-MM-DD.');
        }

        if ($end->lessThan($start)) {
            throw new \InvalidArgumentException('The end date is before the start date.');
        }

        if ($start->diffInDays($end) + 1 > self::MAX_DAYS) {
            throw new \InvalidArgumentException(
                'That window is longer than ' . self::MAX_DAYS . ' days. Reconcile a shorter period; '
                . 'a run that cannot finish on this host reports nothing at all.'
            );
        }

        return new self($start, $end);
    }

    /** The last N days, ending today. The default the screen offers. */
    public static function lastDays(int $days): self
    {
        $days = max(1, min($days, self::MAX_DAYS));
        $end = CarbonImmutable::now('UTC');

        return self::between($end->subDays($days - 1)->toDateString(), $end->toDateString());
    }

    /**
     * Widened by the grace. Never sent to a provider, and NOT used by the two
     * phases that conclude from absence.
     *
     * This is the subtle half. Widening is safe wherever the answer is found by
     * looking something UP — "is there an order behind this reference", "does
     * this order have any payment at all" — because a wider net there only
     * finds more true matches.
     *
     * It is not safe where the answer is "we did not see it". The provider was
     * asked for the strict window; a local row twelve hours past the end of it
     * was never in scope for that question, and reporting it as unconfirmed
     * would be a false alarm generated by the grace itself, once per midnight,
     * for ever. Reconciler::stepLocalPayments spells that out at the query it
     * applies to.
     */
    public function localFrom(): CarbonImmutable
    {
        return $this->from->subHours(self::GRACE_HOURS);
    }

    public function localTo(): CarbonImmutable
    {
        return $this->to->addHours(self::GRACE_HOURS);
    }

    /** Stable across processes — it is half of the run key. */
    public function key(): string
    {
        return $this->from->toDateString() . '..' . $this->to->toDateString();
    }

    public function days(): int
    {
        return (int) $this->from->diffInDays($this->to) + 1;
    }
}
