<?php

declare(strict_types=1);

use App\Support\SeededPolicyPages;
use App\Support\Url;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * The old shop's policy pages, in the owner's own words. (Lane TP)
 *
 * GENERATED by tools/tp-make-migration.php from docs/tp-source/<slug>.txt —
 * the text the owner pasted from kbeautybliss.com himself, kept verbatim.
 * App\Support\PastedPolicyText decides the structure (title, subheadings,
 * bullets, paragraphs, the mailto link) and changes no word;
 * OwnerPolicyPagesTest holds this file to that.
 *
 * ONLY A ROW STILL HOLDING THE SEEDED PLACEHOLDER IS WRITTEN —
 * App\Support\SeededPolicyPages::isSeeded() compares its words with the
 * seed's. A page the owner has edited in Pages → User pages, or one that does
 * not exist, is left exactly as it is, and a re-run changes nothing.
 *
 * ARABIC IS NOT WRITTEN. Pages carry Arabic title and content fields (the
 * translations table, Pages → User pages → Edit → Arabic), but no Arabic text
 * was supplied and none is invented; the Arabic shop prints the English until
 * one is entered there.
 *
 * No route changes: 2027_09_05_200200_clear_caches_policy_links is the
 * package's cache companion.
 */
return new class extends Migration
{
    private const PAGES = [
        'delivery' => [
            'title' => 'Shipping &amp; Delivery',
            'content' => <<<'HTML'
<p>At K-Beauty Bliss, we are committed to delivering your orders swiftly and efficiently, both locally and internationally. Below, you’ll find all the essential details regarding our delivery services:</p>
<h3>Local Delivery:</h3>
<p>For orders within UAE, we offer delivery to your doorstep. Once your order is placed, we offer delivery within only 1-3 days all over UAE.</p>
<p>For any inquiries or assistance regarding local delivery, feel free to reach out to our dedicated customer support team.</p>
<h3>International Delivery:</h3>
<p>For our valued customers worldwide, we extend our delivery services to various international destinations.</p>
<p>After placing your order, please allow 2-5 business days for processing before shipment. International delivery times may vary depending on your country’s customs regulations and local postal services. Typically, delivery can be expected within 7-14 business days from the date of dispatch.</p>
<p>To ensure a smooth delivery experience, we collaborate with reputable international carriers who prioritize the safety and timely delivery of your packages. Once your order is shipped, you will receive a shipping confirmation email with a tracking number, enabling you to track your package every step of the way.</p>
<p>Please note that additional customs duties, taxes, or import fees may apply depending on your country’s regulations. These charges are the responsibility of the recipient and are not included in the total purchase price or shipping cost.</p>
<h3>Customs / Import</h3>
<ul>
<li>For international orders, please check your country’s and city’s import policy before placing the order. In case of any custom or import restrictions, K-Beauty Bliss will not be responsible once the order has been shipped.</li>
<li>If customers refused to pay the customs tax, that it is a part of customers responsibility, refund is NOT possible in this case.</li>
<li>Please note that after it is confirmed that customers refuse to pay customs tax until the determined period decided by the shipping company, the whole package will be disposed of, and even when customers change their mind and want to pay it, as it is already too late, refund or redelivery is not possible.</li>
<li>In case of incorrect address or contact information on customers’ order, we will send an email requesting the correct information. If customers fail to provide the required information within the determined period decided by the shipping company, the whole package will be returned or disposed of.</li>
<li>Please be aware that refund or redelivery is NOT possible in this case.</li>
</ul>
<p>For any inquiries or assistance regarding international delivery, please don’t hesitate to contact our customer support team. We’re here to assist you throughout the shipping process and ensure your complete satisfaction with your K-Beauty Bliss purchase.</p>
<p>Thank you for choosing K-Beauty Bliss . We look forward to delivering exceptional products right to your doorstep, wherever you may be!</p>
HTML,
        ],
        'refund_returns' => [
            'title' => 'Refund and Returns Policy',
            'content' => <<<'HTML'
<p>Unfortunately, we cannot offer refunds or exchanges due to hygiene reasons, as all of our products fall within the skincare, personal care, and makeup categories.</p>
<p>We are happy to make any changes to your order before it is dispatched.</p>
<p>For further concerns, please email us at <a href="mailto:info@kbeautybliss.com">info@kbeautybliss.com</a></p>
HTML,
        ],
        'privacy-policy' => [
            'title' => 'Privacy Policy',
            'content' => <<<'HTML'
<p>We are committed to protecting your privacy. We hope that you will take the time to read this privacy policy, which explains what information we collect from you and how we use that information. By using our website or by purchasing products or services from us, you agree to be bound by this privacy policy.</p>
<h3>What Information We Collect:</h3>
<p>We receive and store certain types of information when you interact with us. Our purpose is to allow the website to work correctly, to evaluate use of the website, and to support website analytics and marketing campaigns.</p>
<p>We may collect your technical information such as your IP address and MAC address to determine what region you are accessing the website from, in order to show you the version of the website that is in your language or covers that region.</p>
<h3>How We Use Your Information:</h3>
<p>We use your information to offer and provide our products and services and to support our core business functions. These include order or service fulfillment, internal business processes, marketing, authentication, loss and fraud prevention, public safety and legal functions, as listed below.</p>
<ul>
<li>To fulfill your orders for products and services and communicate with you about those orders.</li>
<li>To register and service your account.</li>
<li>To provide customer service.</li>
<li>To protect the security or integrity of our websites and mobile app and our business.</li>
<li>To help us improve and customise our product and service offerings, website, and advertising, including through data analytics. A traffic and user behavior auditing system operated by Google Analytics is used on our website. Please see the Google Analytics website for information about Google Analytics, the Google Analytics auditing system, and the Google Analytics’ privacy policy.</li>
</ul>
<h3>How We Protect Your Information:</h3>
<p>To protect against the loss, misuse, and alteration of the information under our control we have implemented security measures on our website.</p>
<p>When you place orders or access your account information, a secure server is employed. All information you input is encrypted by the secure server layer (SSL) before it is sent to us and all the customer data we collect is similarly protected against unauthorised access.</p>
<p>K-Beauty Bliss cannot be and is not responsible for unauthorised access to information by hackers or others who have obtained such access through illegal measures.</p>
<p>“Phishing” is a scam designed to steal your personal information. If you receive an e-mail that looks like it might be from K-Beauty Bliss asking for your personal information, do not respond. K-Beauty Bliss would not request your password, username, credit card information, or other personal information through e-mail.</p>
<h3>How Long We Keep Your Information:</h3>
<p>We will only store your information as long as necessary to fulfil the purposes for which the information is collected and processed or, where applicable law provides for longer storage and retention periods, for the storage and retention period required by law. After that your personal information will be deleted.</p>
<p>We may disclose your personal information if we are required by law to do so or if you violate our Terms of Service.</p>
<h3>Age of Consent:</h3>
<p>By using this site, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence, and you have given us your consent to allow any of your minor dependents to use this site.</p>
<h3>Privacy Policy Changes:</h3>
<p>We reserve the right to modify this privacy policy at any time, so please review it frequently. Changes and clarifications will take effect immediately upon their posting on the website.</p>
<p>Questions about the Privacy Policy should be sent to us at <a href="mailto:info@kbeautybliss.com">info@kbeautybliss.com</a></p>
HTML,
        ],
        'faqs' => [
            'title' => 'Frequently Asked Questions',
            'content' => <<<'HTML'
<h2>PAYMENT OPTIONS</h2>
<h3>Which payment methods do you accept?</h3>
<p>We accept all major credit/debit cards, and provide Cash On Delivery within the UAE. Additionally, we have flexible payment option through Tabby.</p>
<h3>Can I change or cancel my order once placed?</h3>
<p>If you want to change or cancel your order, kindly reach out to us at <a href="mailto:info@kbeautybliss.com">info@kbeautybliss.com</a>. We'll do our best to assist you. However, once our warehouse team has processed your order, we regret that we cannot accommodate any modifications or cancellations.</p>
<h2>SHIPPING AND DELIVERY</h2>
<h3>What's the estimated delivery time for my order?</h3>
<p>All Orders usually ship within 1-3 business days. While delays might occur on public holidays or due to unforeseen circumstances, we strive to deliver your order as promptly as possible.</p>
<h3>What are your delivery charges?</h3>
<p>Delivery charges will be calculated during checkout. We provide free delivery all over UAE for orders over AED 199.</p>
<h2>SKINCARE</h2>
<h3>Are all your products authentic?</h3>
<p>We guarantee that all our beauty products are a 100% authentic. We only work with K-beauty brands and their official suppliers to make sure our products are authentic and high-quality.</p>
<h3>Which K-Beauty brands do you carry?</h3>
<p>We have more than 40 top k-beauty brands available on our website, If you can't find your favorite brand, send us a message at <a href="mailto:info@kbeautybliss.com">info@kbeautybliss.com</a>.</p>
<h3>What should i do if the product i want to buy is out of stock?</h3>
<p>There are occasions when certain items may be temporarily out of stock. Please use the 'Notify Me When Back In Stock' tab on the product page, and we'll promptly notify you via email once it's available again.</p>
<h2>RETURNS/EXCHANGES</h2>
<h3>What is your return and exchange policy?</h3>
<p>We want you to be fully satisfied with your purchase at K-Beauty Bliss. Please check our <a href="/refund_returns/">Returns Policy page</a> for more information.</p>
HTML,
        ],
    ];

    public function up(): void
    {
        // A link to a page of this shop is stored root-relative and carries the
        // deployment's base path (empty on the live shop), as OldSiteLinks
        // writes every imported link. mailto: is not touched.
        $base = rtrim(Url::raw('/'), '/');

        foreach (self::PAGES as $slug => $page) {
            $row = DB::table('pages')->where('slug', $slug)->first();

            if ($row === null || ! SeededPolicyPages::isSeeded($slug, $row->content)) {
                continue;
            }

            DB::table('pages')->where('id', $row->id)->update([
                'title' => $page['title'],
                'content' => str_replace('href="/', 'href="'.$base.'/', $page['content']),
                'updated_at' => now(),
            ]);
        }
    }

    public function down(): void
    {
        // Deliberately empty, like the seeds before it: the owner's own words
        // are not taken back off his shop by a rollback.
    }
};
