<?php

declare(strict_types=1);

namespace App\Support;

/**
 * Country names and the region groupings the delivery picker offers.
 *
 * Not a full ISO list — the ninety-odd here are the ones a shop in this region
 * plausibly ships to. Adding a country is one line; carrying 249 of them to
 * make a point is a list nobody maintains.
 */
class Countries
{
    /** @var array<string, string> */
    public const NAMES = [
        'DZ' => 'Algeria',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BE' => 'Belgium',
        'BR' => 'Brazil',
        'BG' => 'Bulgaria',
        'KH' => 'Cambodia',
        'CA' => 'Canada',
        'CL' => 'Chile',
        'CN' => 'China',
        'CO' => 'Colombia',
        'HR' => 'Croatia',
        'CY' => 'Cyprus',
        'CZ' => 'Czechia',
        'DK' => 'Denmark',
        'EG' => 'Egypt',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FI' => 'Finland',
        'FR' => 'France',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GR' => 'Greece',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JP' => 'Japan',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KW' => 'Kuwait',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LY' => 'Libya',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'MT' => 'Malta',
        'MX' => 'Mexico',
        'MA' => 'Morocco',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'NZ' => 'New Zealand',
        'NG' => 'Nigeria',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PS' => 'Palestine',
        'PH' => 'Philippines',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'QA' => 'Qatar',
        'RO' => 'Romania',
        'RU' => 'Russia',
        'SA' => 'Saudi Arabia',
        'RS' => 'Serbia',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'ZA' => 'South Africa',
        'KR' => 'South Korea',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syria',
        'TW' => 'Taiwan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TN' => 'Tunisia',
        'TR' => 'Türkiye',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UZ' => 'Uzbekistan',
        'VN' => 'Vietnam',
        'YE' => 'Yemen',
    ];

    /** Region => codes, for the bulk chips on the picker. */
    public const REGIONS = [
        'GCC' => ['AE', 'SA', 'KW', 'QA', 'BH', 'OM'],
        'Middle East' => ['AE', 'SA', 'KW', 'QA', 'BH', 'OM', 'IQ', 'JO', 'LB', 'SY', 'YE', 'IR', 'PS', 'TR', 'CY'],
        'North Africa' => ['EG', 'MA', 'DZ', 'TN', 'LY', 'SD'],
        'Africa' => ['NG', 'KE', 'ZA', 'GH', 'ET', 'TZ', 'UG'],
        'Europe' => ['GB', 'IE', 'FR', 'DE', 'ES', 'IT', 'PT', 'NL', 'BE', 'LU', 'CH', 'AT', 'SE', 'NO', 'DK', 'FI', 'IS', 'PL', 'CZ', 'SK', 'HU', 'RO', 'BG', 'GR', 'HR', 'SI', 'RS', 'UA', 'MT', 'EE', 'LV', 'LT'],
        'South Asia' => ['IN', 'PK', 'BD', 'LK', 'NP', 'MV'],
        'East Asia' => ['CN', 'HK', 'TW', 'JP', 'KR'],
        'South-East Asia' => ['SG', 'MY', 'ID', 'TH', 'VN', 'PH', 'KH'],
        'Oceania' => ['AU', 'NZ'],
        'Americas' => ['US', 'CA', 'MX', 'BR', 'AR', 'CL', 'CO'],
    ];
}
