<?php

declare(strict_types=1);

namespace App\Support;

/**
 * The category header's PHONE-AND-LAPTOP-APART rules, derived from its own
 * stylesheet. (Lane QC)
 *
 * THE OWNER: "i need the same designs on backend to choose the category banner
 * designs, text style etc and for mobile also."
 *
 * A header whose phone and laptop choices are the same carries one class per
 * choice (`kbb-th--a-center`, `kbb-th--t-frost`, ...) and the stylesheet's
 * rules apply as they always have. A header whose choices DIFFER carries
 * `kbb-th--split` and every one of those words twice -- `kbb-th--p-a-start`
 * for the phone, `kbb-th--l-a-center` for the laptop (TitleHeader::forModel).
 *
 * This class writes the rules those prefixed words need: EVERY rule in
 * kbb-title-header.css whose selector names a choice word, copied once with
 * `p-` inside the phone's media query and once with `l-` inside the laptop's.
 * The two queries are exact complements -- `(min-width:900px)` and `not all
 * and (min-width:900px)` -- so at any width exactly one copy applies, and a
 * phone rule (the frosted panel's padding, say) cannot leak onto a laptop
 * whose choice has none. No script, nothing measured: the browser picks.
 *
 * GENERATED, NOT HAND-COPIED. The copies are appended to the stylesheet between
 * BEGIN and END by tools/qc-split-css.php, and QcCategoryHeaderDevicesTest
 * rebuilds them from the rules above BEGIN and requires the file to match byte
 * for byte -- so a rule edited above without re-running the tool is red, and a
 * phone that would quietly render the old version of a treatment cannot ship.
 *
 * The parser is deliberately small: it reads THIS stylesheet, which is plain
 * rules, one @media and one @supports, and comments. It is not a CSS parser
 * for anything else.
 */
final class TitleHeaderSplitCss
{
    public const BEGIN = '/* ── Lane QC: phone and laptop apart. GENERATED by tools/qc-split-css.php from the rules above -- edit those and re-run it, never this block. ── */';

    public const END = '/* ── end of the generated phone-and-laptop rules ── */';

    public const PHONE_QUERY = '@media not all and (min-width:900px)';

    public const LAPTOP_QUERY = '@media (min-width:900px)';

    /** The words a choice puts on the header, and nothing else. */
    public const CHOICE_WORD = '/\.kbb-th--(light|dark|a-(?:start|center|end)|t-(?:shadow|fade|frost|label|none)|box-(?:blush|cream|mint|lilac|plain|custom))(?![\w-])/';

    /**
     * The stylesheet with its generated block rebuilt from the rules above it.
     */
    public static function apply(string $css): string
    {
        $source = self::source($css);

        return rtrim($source)."\n\n".self::BEGIN."\n".self::build($source).self::END."\n";
    }

    /** Everything above the generated block (the whole file when it has none). */
    public static function source(string $css): string
    {
        $at = strpos($css, self::BEGIN);

        return $at === false ? $css : substr($css, 0, $at);
    }

    /** The generated block itself, as it stands in a file. */
    public static function generated(string $css): ?string
    {
        $from = strpos($css, self::BEGIN);
        $to = strpos($css, self::END);

        if ($from === false || $to === false) {
            return null;
        }

        $from += strlen(self::BEGIN) + 1;

        return substr($css, $from, $to - $from);
    }

    public static function build(string $source): string
    {
        $nodes = self::parse(self::stripComments($source));
        $out = '';

        foreach (['p' => self::PHONE_QUERY, 'l' => self::LAPTOP_QUERY] as $p => $query) {
            $out .= $query."{\n";

            foreach ($nodes as $node) {
                $out .= self::emit($node, $p);
            }

            // What only a split header needs: a device whose box has colours
            // of its own takes them from its own pair of properties, and E,
            // the one box style with no icons, hides the icon layer the other
            // device's style asked for.
            $out .= '.kbb-th--split.kbb-th--'.$p.'-own{--kbb-th-bg:var(--kbb-th-'.$p.'-bg);--kbb-th-ic:var(--kbb-th-'.$p."-ic)}\n";
            $out .= '.kbb-th--'.$p."-box-plain .kbb-th__icons{display:none}\n";
            $out .= "}\n";
        }

        return $out;
    }

    /** @param array{0: string, 1: string, 2: mixed} $node */
    private static function emit(array $node, string $p): string
    {
        [$kind, $head, $body] = $node;

        if ($kind === 'rule') {
            if (preg_match(self::CHOICE_WORD, $head) !== 1) {
                return '';
            }

            return preg_replace(self::CHOICE_WORD, '.kbb-th--'.$p.'-$1', $head).'{'.$body."}\n";
        }

        // Only an @supports block is carried (the frosted panel's fallback).
        // The stylesheet's own @media blocks hold no choice word and are the
        // device switch itself, which must not be nested inside another.
        if (! str_starts_with($head, '@supports')) {
            return '';
        }

        $inner = '';

        foreach ($body as $child) {
            $inner .= self::emit($child, $p);
        }

        return $inner === '' ? '' : $head."{\n".$inner."}\n";
    }

    private static function stripComments(string $css): string
    {
        return (string) preg_replace('#/\*.*?\*/#s', '', $css);
    }

    /**
     * Top-level statements as [kind, head, body]: a rule's body is its
     * declarations with whitespace collapsed; an at-rule's is its children.
     *
     * @return list<array{0: string, 1: string, 2: mixed}>
     */
    private static function parse(string $css): array
    {
        $nodes = [];
        $i = 0;
        $n = strlen($css);

        while ($i < $n) {
            $open = strpos($css, '{', $i);

            if ($open === false) {
                break;
            }

            $head = self::squash(substr($css, $i, $open - $i));
            $depth = 1;
            $j = $open + 1;

            while ($j < $n && $depth > 0) {
                if ($css[$j] === '{') {
                    $depth++;
                } elseif ($css[$j] === '}') {
                    $depth--;
                }
                $j++;
            }

            $inner = substr($css, $open + 1, $j - $open - 2);

            $nodes[] = str_starts_with($head, '@')
                ? ['at', $head, self::parse($inner)]
                : ['rule', $head, self::squash($inner)];

            $i = $j;
        }

        return $nodes;
    }

    private static function squash(string $s): string
    {
        return trim((string) preg_replace('/\s+/', ' ', $s));
    }
}
