#!/usr/bin/env bash
#
# Turn the committed HTML previews into PNGs the owner can look at.
#
# docs/email-previews/*.html are regenerated by tests/Feature/OrderEmailPreviewsTest.php
# every time the suite runs, so they are always the real message body. This
# script only photographs them, at the two widths that matter:
#
#   *.png          700px — a desktop mail client, roughly Gmail's reading pane.
#   *.phone.png    400px — a phone held in one hand, which is where most of
#                  these are read and the width the Qty column had to survive.
#
# WHY A WRAPPER DOCUMENT. The previews are message BODIES: no <html>, no <head>,
# no <body>, because Symfony Mime wraps the part and every client re-wraps it
# (see resources/views/emails/layout.blade.php). A renderer needs a document, so
# one is built here around an untouched copy of the body. Nothing in the body is
# altered — what is photographed is byte-for-byte what is sent.
#
# WHAT THIS IS NOT. wkhtmltoimage is WebKit. It is a reasonable stand-in for
# Apple Mail and for the webmail clients, and it is a WORSE renderer than most
# of them, which is the useful direction to be wrong in. It is NOT Outlook:
# Outlook for Windows renders with Word and no tool on a Linux box reproduces
# that. The layout is built for Word's limits — tables, inline styles, bgcolor
# attributes, no flex, no grid, no media queries — but the only way to know is
# to send one and look.
#
# Usage, from the repository root:
#
#   vendor/bin/pest tests/Feature/OrderEmailPreviewsTest.php   # regenerate HTML
#   bash tools/render-email-previews.sh                        # then photograph

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIR="$ROOT/docs/email-previews"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if ! command -v wkhtmltoimage >/dev/null 2>&1; then
    echo "wkhtmltoimage is not installed. Install it, or open the .html files in a browser." >&2
    exit 1
fi

shopt -s nullglob

for src in "$DIR"/*.html; do
    name="$(basename "$src" .html)"

    {
        printf '<!doctype html><meta charset="utf-8">'
        # No styling of our own beyond the page ground: anything added here
        # would be a rule the real mail client does not have.
        printf '<body style="margin:0;padding:0;background:#FFF8F5;">'
        cat "$src"
        printf '</body>'
    } > "$TMP/$name.html"

    for width in 700 400; do
        out="$DIR/$name.png"
        [ "$width" = "400" ] && out="$DIR/$name.phone.png"

        wkhtmltoimage \
            --quiet \
            --enable-local-file-access \
            --format png \
            --width "$width" \
            --quality 82 \
            "$TMP/$name.html" "$out"

        echo "$out"
    done
done
