/*
 * Lane SS: /super-sale/ with its banner and strip, and Pages → Page banners,
 * photographed in Chromium at 390 and 1280 with measurements.
 *
 *   SS_BASE=http://127.0.0.1:10121 node tools/ss-shots.cjs
 *
 * Run against a preview booted by tools/ss-preview.sh on a tree with
 * `php tools/ss-wire.php` applied (the integrator's edits), reverted afterwards.
 * It drives the console rather than posing it: the pictures are chosen through
 * the real Media Library picker and stored with the real Save button. The
 * pictures themselves are PLACEHOLDERS generated by tools/ss-seed.php.
 */
const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

const CHROME = '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const BASE = process.env.SS_BASE || 'http://127.0.0.1:10121';
const OUT = path.resolve(__dirname, '..', 'docs/ss-shots');
const rows = [];

async function measureShop(page) {
  return page.evaluate(() => {
    const px = (el, p) => (el ? parseFloat(getComputedStyle(el)[p]) : null);
    const pb = document.querySelector('.kbb-pb');
    const img = document.querySelector('.kbb-pb-img img');
    const strip = document.querySelector('.kbb-pb-strip');
    const li = document.querySelectorAll('.kbb-pb-strip li');
    const ic = document.querySelector('.kbb-pb-ic');
    const slugs = [...new Set([...document.querySelectorAll('.kbb-pgrid a[href*="/product/"]')].map(a => a.getAttribute('href').replace(/^.*\/product\/([^/]+)\/.*$/, '$1')))];
    return {
      viewport: document.documentElement.clientWidth,
      scrollWidth: document.documentElement.scrollWidth,
      bannerBlocks: document.querySelectorAll('.kbb-pb').length,
      imgSrc: img ? img.currentSrc.replace(location.origin, '') : null,
      imgW: img ? img.getBoundingClientRect().width : null,
      imgH: img ? img.getBoundingClientRect().height : null,
      stripW: strip ? strip.getBoundingClientRect().width : null,
      stripH: strip ? strip.getBoundingClientRect().height : null,
      stripFont: px(strip, 'fontSize'),
      stripBg: strip ? getComputedStyle(strip).backgroundColor : null,
      stripRows: li.length ? new Set([...li].map(l => Math.round(l.getBoundingClientRect().top))).size : 0,
      tickPx: ic ? ic.getBoundingClientRect().width : null,
      items: [...li].map(l => l.textContent.trim()),
      firstProducts: slugs.slice(0, 6),
    };
  });
}

async function shop(page, name) {
  for (const w of [390, 1280]) {
    await page.setViewportSize({ width: w, height: w === 390 ? 844 : 900 });
    await page.goto(`${BASE}/super-sale/`, { waitUntil: 'networkidle' });
    await page.waitForTimeout(400);
    const m = await measureShop(page);
    await page.screenshot({ path: `${OUT}/${name}-${w}.png`, fullPage: false });
    rows.push({ shot: `${name}-${w}`, ...m });
    console.log(JSON.stringify({ shot: `${name}-${w}`, ...m }));
  }
}

async function admin(page, name, w) {
  await page.setViewportSize({ width: w, height: w === 390 ? 844 : 1000 });
  await page.waitForTimeout(500);
  const m = await page.evaluate(() => ({
    viewport: document.documentElement.clientWidth,
    scrollWidth: document.documentElement.scrollWidth,
    crumb: document.querySelector('#crumb')?.textContent ?? null,
    title: document.querySelector('#ptitle')?.textContent ?? null,
    sidebarRows: document.querySelectorAll('#nav [data-go="pagebanners"]').length,
    openTab: document.querySelector('.pbs-tab[aria-selected="true"]')?.textContent ?? null,
    stageStripH: document.querySelector('.pbs-stage .kbb-pb-strip')?.getBoundingClientRect().height ?? null,
  }));
  await page.screenshot({ path: `${OUT}/admin-${name}-${w}.png`, fullPage: true });
  rows.push({ shot: `admin-${name}-${w}`, ...m });
  console.log(JSON.stringify({ shot: `admin-${name}-${w}`, ...m }));
}

async function pick(page, key, file) {
  await page.click(`[data-pbs-pick="${key}"]`);
  await page.waitForSelector('#mp-q', { state: 'visible' });
  await page.fill('#mp-q', file.replace(/\.png$/, ''));
  await page.waitForTimeout(900);
  await page.click(`.mp-tile[data-mp-url$="${file}"], [data-mp-url$="${file}"]`);
  await page.click('#mp-ok');
  await page.waitForTimeout(300);
}

(async () => {
  fs.mkdirSync(OUT, { recursive: true });
  const browser = await chromium.launch({ executablePath: CHROME });
  const ctx = await browser.newContext({ viewport: { width: 1280, height: 1000 } });
  const page = await ctx.newPage();
  page.on('pageerror', (e) => console.log(JSON.stringify({ pageError: String(e) })));

  // 1. What ships: the strip, no picture (nobody has uploaded one).
  await shop(page, 'super-sale-shipped');

  // 2. The console.
  await page.goto(`${BASE}/admin/login`, { waitUntil: 'networkidle' });
  await page.fill('input[name=email]', 'owner@preview.test');
  await page.fill('input[name=password]', 'preview-secret-1');
  await Promise.all([page.waitForNavigation({ waitUntil: 'networkidle' }), page.click('button[type=submit], input[type=submit]')]);

  await page.goto(`${BASE}/admin?go=pagebanners`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(1500);
  await admin(page, 'banners-before', 1280);
  await admin(page, 'banners-before', 390);

  await page.setViewportSize({ width: 1280, height: 1000 });
  await pick(page, 'img_d', 'placeholder-d.png');
  await pick(page, 'img_m', 'placeholder-m.png');
  await page.fill('[data-pbs-k="alt"]', 'Super Sale — shop now, pay later — coupon code GLOW');
  await page.fill('[data-pbs-k="link"]', '/super-sale/');
  await admin(page, 'banners-after-phone-preview', 1280);
  await page.click('button[data-pbs-dev="d"]');
  await admin(page, 'banners-after-desktop-preview', 1280);
  await admin(page, 'banners-after', 390);
  await page.setViewportSize({ width: 1280, height: 1000 });
  await page.click('[data-pbs-save]');
  await page.waitForTimeout(1200);

  await page.click('[data-pbs-tab="pages"]');
  await admin(page, 'where-they-show', 1280);
  await admin(page, 'where-they-show', 390);
  await page.setViewportSize({ width: 1280, height: 1000 });
  await page.click('[data-pbs-tab="sale"]');
  await admin(page, 'super-sale-products', 1280);
  await admin(page, 'super-sale-products', 390);

  // 3. The shop with the (placeholder) picture saved.
  await shop(page, 'super-sale-with-banner');

  fs.writeFileSync(`${OUT}/measurements.json`, JSON.stringify(rows, null, 1));
  await browser.close();
})();
